[package]
name = "sudoku-cli"
version = "0.1.0"
authors = ["ObliqueMotion"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1

[dependencies]
ansi-escapes = "0.1.0"